### ISSUE TITLE
Progress in Weather Data

### ISSUE THREAD

**Issue by camilavargasp** [padl-project/miller_ter_kuile_terrestial_data#2]
## Friday, August 6
For the most part, all the weather data has been cleaned!

**Next Steps**

- [x]  need to check the NaN vs NA in the weather tables
- [x] upload to drive
- [x] register metadata in a new issue
- [x] upload to EDI

**Comment by ronanfdavis** [comment]
> ##Uploaded susccesfully: need to ceck NaN. When saving csv they tun into NAs. Do we need to keep them as NaN?

As far as this note goes - NaN was the original not available code in the spreadsheets, so I extended that pattern to the other missing cells. I don't know of any firm rules or reason why it's NaN or NA, so my instinct would be that it's okay to leave them as the converted NAs they turn into during saving

**Comment by camilavargasp** [comment]
but what about the note in the spreadsheet saying that NaN is Not a Number?
We can set them as NaN which is actually a numeric class. 
@bdavis20, do you think that would make it more transparent?

**Comment by camilavargasp** [comment]
Ana's Miller-ter Kuile answer
These were data collected by field station managers and/or US Fish and Wildlife managers over the years. So - your guess might be as good as mine on what missing values mean in this dataset. I can track down the actual email exchange when I got these data from folks to see if there is any more info - though I bet that Jenn has you in contact with all the right people to provide a little more metadata on these.

When looking at this dataset, it looks like different people had different missing value codes at various times that meant "this measurement wasn't taken at this time". So it looks like both "NAN" and "." were used to indicate this on the weather data station 15-minute dataset (2010-2014 = NAN, 2015-2016 = .). I would read it as "this sensor was not collecting data at this time, either because it was down or did not exist". So - a missing value code is how I would read it. Hope that helps?

I ended up only using some precipitation data for the project I tracked those down for (Lafferty et al. 2018 Invasive mosquito extinction paper) and those don't have any missing values. I *think* I remember getting these data from both Stefan Kroplidowski and the field station manager at the time, Perry.

**Comment by camilavargasp** [comment]
As for now we registered all the missing data (NAN, NAs, serv. and . )as NAs

**Comment by camilavargasp** [comment]
** To keep in mind**
 Do we hold on to weather data in case there is more data around that we want to combine?
Alternatively, publish what we have and then update the package if needed.

**Comment by ronanfdavis** [comment]
I'm not sure, that's really the main question with all of the packages we have ready/near ready. I don't think there'll be more weather data added on as a direct addendum to this dataset.

I haven't processed a revision through EDI yet, but from their workshop and training it seems a fairly painless process

**Comment by camilavargasp** [comment]
Weather data has been successfully uploaded to EDI

[Data package edi.966.2](https://portal.edirepository.org/nis/metadataviewer?packageid=edi.966.2)
