### ISSUE TITLE
Weather data Metadata

### ISSUE THREAD

**Issue by camilavargasp** [padl-project/miller_ter_kuile_terrestial_data#3]
The weather data consist of two files:
- Weather tables
- Monthly rainfall

### Weather table
**Description**
Weather station data from Palmyra Atoll courtesy of TNC and USFWS. Data was made available to PADL by Ana Miller-ter Kuile

**Associated publications**
- Lafferty et al. 2018
- Lafferty, K. D., McLaughlin, J. P., Gruner, D. S., Bogar, T. A., Bui, A., Childress, J. N., … Young, H. S. (2018). Local extinction of the Asian tiger mosquito ( Aedes albopictus ) following rat eradication on Palmyra Atoll. Biology Letters, 14, 1–5. doi: [10.1098/rsbl.2017.0743](10.1098/rsbl.2017.0743)
- Miller-ter Kuile et al. 2020
- Miller-ter Kuile, A., Orr, D., Bui, A., Dirzo, R., Klope, M., McCauley, D., … Young, H. (2020). Impacts of rodent eradication on seed predation and plant community biomass. Biotropica. doi: [10.1111/btp.12864](10.1111/btp.12864)

|Column name | Description| Value range|
|--------------|------------|-------------|
|year | year data was collected | 2010 to 2016 |
|date|  day of the year data was collected| October 16 2010 to September 28 2016
|time| time of the day data was collected, tz = HAST | Data is collected daily every 15 min|
|batt_avg| Battery average in Volts | 5.8 - 13.4|
air_tc_avg|  Average of air temperature in Celsius | 21.79 - 32.39|
|rh| Percentage of Relative Humidity | 38.91 - 98.40 |
|par_den_avg| Photosynthetically Active Radiation, average density, micro-mol/s/square-meter | 0 - 2,432|
|par_tot_tot| Total Photosynthetically Active Radiation, mmol/square-meter| 
|bp_avg| Average Barometric Pressure, kPa | 0 - 2,188.7
|slr_avg|  solar radiation flux density in watts per meters squared| per meters squared    |0 -1,445|
|slr_tot|  slr_tot is total solar radiation flux density in kilojoules per m2 | 0 - 1,094|
|wind_speed_avg| Aveagage wind speed, meters by second| 0 - 11.91|
|wind_speed_max| maximum wind speed, meters by second| 0 - 19.85|
|wind_speed_min| minimum wind speed, meters by second| 0 - 9.35|
|wind_dir| wind direction, degrees | 0.024 - 351|

**Equipment Notes**
- Logger: Campbell Scientific, CR800 
- AirT and RH: Vaisala, Model HMP45C (Oct 16, 2010, to June 25, 2013) 
- AirT and RH: Vaisala, Model HC2S3C (June 26 2013 to present)
- PAR: Photosynthetically Active Radiation, Li-Cor, Model Li-190SB (until 2014, thereafter PAR: No longer being recorded (replaced by pranometer readings) 
- Pyranometer: Hukseflux LP02-00 (serial # 44837) 
- Barometric Pressure: Setra, Model 278 (Campbell Scientific Model CS100) 
- Anemometer: 03002 R.M. Young Wind Sentry Set (mod. 03101 anemometer; mod. 03301 wind vane) 
- Rain Gage: Met One, Model 380C Solar Panel: BP Solar, Model SX310M 

### Rainfall data
Daily rainfall in millimeters from July 1, 2008, to October 31, 2017.

|Column name | Description| Value range|
|--------------|------------|-------------|
|year| year data was collected | 2008 - 2017|
|month| corresponding month| Jan - Dec|
|day| day of the month| 1 - 31|
|rainfall| millimeters of rainfall each day | 0 - 221.6|

**Comment by camilavargasp** [comment]
@bdavis20 Do you know what **slr ** stands for in the weather table data?

**Comment by ronanfdavis** [comment]
SLR is SoLar Radiation flux density
So slr_avg is average solar radiation flux density in watts per meters squared, slr_tot is total solar radiation flux density in kilojoules per meters squared

This description breakdown looks great!
